### ISSUE TITLE
Error reading mgf file

### ISSUE THREAD

**Issue by veitveit** [michabirklbauer/internal_ions#40]
I tried a few older mgf files and the following error pops up quite consistently:
![image](https://github.com/michabirklbauer/internal_ions/assets/15800709/569f8b38-c69b-4370-a3fc-742934069193)

For instance for this file:
https://ftp.pride.ebi.ac.uk/pride/data/archive/2024/05/PXD051750/WT08Th.mzid_WT08Th.MGF

**Comment by michabirklbauer** [comment]
So - I had a look at this and the problem here is that for some of the precursors the intensity is missing, e.g. if you look at the mgf file the first spectrum has no precursor intensity (or there is a missing space between m/z and intensity).

The question is how we want to handle that?

Another problem in this MGF is that is has no scan numbers - or rather they are hidden in the title and can't be parsed with pyteomics.

So another question, how do we handle that?

Do we allow the user to specify a regex pattern for parsing? E.g. I have done something like that [here](https://github.com/hgb-bin-proteomics/Proteome_Discoverer_MGF_Scan_Number_Repair_Tool/blob/master/scan_nr_repair_tool.py) where it falls back to a user given regex if the scan number can't be parsed by pyteomics.
In any case, I don't know how Fragannot and Fraggraph handle this, so it might be wasted effort anyway.

**Comment by veitveit** [comment]
These are quite old files so maybe this is just solved by using more recent conversion tools. 

I think we used msconvert from ProteoWizard. So maybe using that tool is creating these artifacts? 

As you say, this might not be a problem. Maybe add a comment about the expected mgf format when this fails?

**Comment by caetera** [comment]
Extra `None` could be handled at a later stage.

Something like this should work (https://github.com/michabirklbauer/internal_ions/blob/8e1763c35109e91f70ec968a9805b5a2672ca80e/util/tab3/plots.py#L43)
```
min_intensity = min([0.0] + [spectrum["precursor"][1] for spectrum in spectra.values() if spectrum["precursor"][1]])
max_intensity = max([0.0] + [spectrum["precursor"][1] for spectrum in spectra.values() if spectrum["precursor"][1]])
```
Ignore all `None` in list comprehension and add to non-empty with some default value (if everything is `None`)

The format from this mgf is certainly not from msconvert.
However, the format of the title itself does not matter as soon as the PSM can be matched to the spectrum file. There are some heuristics in place to do this. Whatever is used as a `SpectrumId` (in MzID or other format) is matched against a plain scan number, a plain title string, or a part of it that follows `index=([0-9]+)` or `scan=([0-9]+)`.
The point is, that the format we expect is that the identification file and the spectrum file use the same notation for _calling_ spectra.

**Comment by michabirklbauer** [comment]
Yeah handling none values directly at the plot level is definitely a good idea!
Will implement that.
Plus, I think I we are not using the intensity at any other stage, so should not really make a difference how we handle this. Except that the plot will look a bit different depending on the specifics.

As for scan numbers, I am hoping it works the way as you say. Otherwise it will get really messy haha 🙃

Thanks for the input!
